// <auto-generated />
namespace Turisticka_Agencija.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Drugamigracija : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Drugamigracija));
        
        string IMigrationMetadata.Id
        {
            get { return "202305291700090_Druga migracija"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
